version: '3'

services:
    db:
        image: mysql:5.6
        volumes:
            - db_data_56:/var/lib/mysql
        ports:
            - "16306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 124
            MYSQL_DATABASE: test 
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: dbpass

    php:
        depends_on:
            - db
        build:
            context: .
            dockerfile: files/php-Dockerfile
        ports:
            - "16080:80"
        volumes:
            - /tmp:/var/www/html

volumes:
    db_data_56:
